name: Check PocketBase Version

on:
  schedule:
    - cron: "0 12 * * *" # Todos los días a las 12 PM UTC
  workflow_dispatch:

jobs:
  update-pocketbase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest PocketBase release
        id: fetch_release
        run: |
          # Obtener la última versión publicada
          LATEST_VERSION=$(curl -s https://api.github.com/repos/pocketbase/pocketbase/releases/latest | jq -r '.tag_name' | sed 's/v//')
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV

      - name: Get current version from Dockerfile
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep -oP '^ARG PB_VERSION=\K.*' Dockerfile)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Check if update is needed
        id: check_update
        run: |
          if [ "${{ env.LATEST_VERSION }}" = "${{ env.CURRENT_VERSION }}" ]; then
            echo "No update needed. Current version (${CURRENT_VERSION}) is already the latest (${LATEST_VERSION})."
            echo "update_needed=false" >> $GITHUB_ENV
          else
            echo "Update needed. Current version: ${CURRENT_VERSION}, Latest version: ${LATEST_VERSION}."
            echo "update_needed=true" >> $GITHUB_ENV
          fi

      - name: Update Dockerfile
        if: ${{ env.update_needed == 'true' }} # Solo ejecuta si hay cambios
        run: |
          sed -i "s/^ARG PB_VERSION=.*/ARG PB_VERSION=${{ env.LATEST_VERSION }}/" Dockerfile
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: update PocketBase to v${{ env.LATEST_VERSION }}"

      - name: Create Pull Request
        if: ${{ env.update_needed == 'true' }} # Solo ejecuta si hay cambios
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-pocketbase-version
          title: "Update PocketBase to v${{ env.LATEST_VERSION }}"
          body: "This PR updates the Dockerfile to use PocketBase v${{ env.LATEST_VERSION }}."
          labels: dependencies
